# Generated by Django 2.0.5 on 2018-06-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('running', 'running'), ('stoped', 'stoped')], default='running', max_length=20)),
                ('tp', models.CharField(choices=[('http', 'http'), ('ping', 'ping'), ('tcp', 'tcp'), ('dig', 'dig')], default='http', max_length=20)),
                ('resut', models.TextField(default='{}')),
            ],
            options={
                'db_table': 'check',
            },
        ),
    ]
