# Generated by Django 2.0.5 on 2018-06-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180517_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'monitor',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['url'], name='url_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type'], name='task_type_idx'),
        ),
    ]
